<script setup lang="ts">
</script>

<template>
  <div class="location-card">
    <div class="card-header">
      <div>
        <p class="section-label">CURRENT LOCATION</p>
        <h3 class="card-title">San Francisco, CA</h3>
      </div>
      <button class="edit-btn">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 256 256"><path fill="currentColor" d="M227.31,73.37,182.63,28.68a16,16,0,0,0-22.63,0L36.69,152A15.86,15.86,0,0,0,32,163.31V208a16,16,0,0,0,16,16H92.69A15.86,15.86,0,0,0,104,219.31L227.31,96a16,16,0,0,0,0-22.63ZM92.69,208H48V163.31l88-88L180.69,120ZM192,108.68,147.31,64l24-24L216,84.68Z"/></svg>
      </button>
    </div>
    
    <div class="map-container">
      <!-- We will inject an image generated by the AI here later, or use background inline -->
      <img src="https://assets.objkt.media/file/assets-003/QmaMhB38M65KST4x6D7B4W3J9dDq7hA7Z7K9Z1bXbQXXs4/artifact" alt="Map of San Francisco" class="map-image" />
    </div>
  </div>
</template>

<style scoped>
.location-card {
  background-color: var(--surface-color);
  border-radius: var(--radius-lg);
  padding: 24px;
  box-shadow: var(--shadow-sm);
  flex: 1;
  display: flex;
  flex-direction: column;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 20px;
}

.section-label {
  font-size: 0.75rem;
  font-weight: 700;
  color: var(--success-green);
  letter-spacing: 1px;
  margin-bottom: 4px;
}

.card-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--text-main);
}

.edit-btn {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background-color: var(--bg-color);
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--success-green);
  transition: var(--transition-fast);
}

.edit-btn:hover {
  background-color: #e6e8eb;
}

.map-container {
  width: 100%;
  height: 160px;
  border-radius: var(--radius-md);
  overflow: hidden;
  background-color: #e8eaed; /* placeholder color */
}

.map-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
</style>
